import Vue from "vue";
import Vuex from "vuex";

Vue.use(Vuex);

export default new Vuex.Store({
  state: {
    products: [
      {
        id: 1,
        discountPrice: 5990,
        fullPrice: 5990,
        discountPercent: 25,
        isHit: true,
        available: true,
        name: "Полное название товара",
      },
      {
        id: 2,
        discountPrice: 5990,
        fullPrice: 5990,
        discountPercent: 25,
        isHit: true,
        available: true,
        name: "Полное название товара в несколько строк для вида с обрывом в конце с длинным текстом, так, чтобы проверить правильность обрывания текста",
      },
      {
        id: 3,
        discountPrice: 5990,
        fullPrice: 5990,
        discountPercent: 25,
        isHit: true,
        available: false,
        name: "Полное название товара в несколько строк для вида с обрывом в конце",
      },
      {
        id: 4,
        discountPrice: 5990,
        fullPrice: 5990,
        discountPercent: 25,
        isHit: true,
        available: true,
        name: "Полное название товара в несколько строк для вида с обрывом в конце",
      },
      {
        id: 5,
        discountPrice: 5990,
        fullPrice: 5990,
        discountPercent: 25,
        isHit: true,
        available: true,
        name: "Полное название товара в несколько строк для вида с обрывом в конце",
      },
      {
        id: 6,
        discountPrice: 5990,
        fullPrice: 5990,
        discountPercent: 25,
        isHit: true,
        available: true,
        name: "Полное название товара в несколько строк для вида с обрывом в конце",
      },
      {
        id: 7,
        discountPrice: 5990,
        fullPrice: 5990,
        discountPercent: 25,
        isHit: true,
        available: true,
        name: "Полное название товара в несколько строк для вида с обрывом в конце",
      },
      {
        id: 8,
        discountPrice: 5990,
        fullPrice: 5990,
        discountPercent: 25,
        isHit: true,
        available: true,
        name: "Полное название товара в несколько строк для вида с обрывом в конце",
      },
      {
        id: 9,
        discountPrice: 5990,
        fullPrice: 5990,
        discountPercent: 25,
        isHit: true,
        available: true,
        name: "Полное название товара в несколько строк для вида с обрывом в конце",
      },
      {
        id: 10,
        discountPrice: 5990,
        fullPrice: 5990,
        discountPercent: 25,
        isHit: true,
        available: true,
        name: "Полное название товара в несколько строк для вида с обрывом в конце",
      },
      {
        id: 11,
        discountPrice: 5990,
        fullPrice: 5990,
        discountPercent: 25,
        isHit: true,
        available: true,
        name: "Полное название товара в несколько строк для вида с обрывом в конце",
      },
      {
        id: 12,
        discountPrice: 5990,
        fullPrice: 5990,
        discountPercent: 25,
        isHit: true,
        available: true,
        name: "Полное название товара в несколько строк для вида с обрывом в конце",
      },
    ],
  },
  getters: {},
  mutations: {},
  actions: {},
  modules: {},
});
